name: Update Gameweek Deadlines

on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes

jobs:
  update-scores:
    runs-on: ubuntu-latest
    steps:
      - name: Call API to update gameweek deadlines
        run: curl -X GET https://www.footiepredictors.com/api/updateGameweekLockStatus
